        # For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration.html

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-6.12

# Local packages, usually specified by relative directory name
packages:
- .
- ./compdata
- ./comptrans
- ./compstrat
# - ../langs/language-csharp-quote
- ../langs/imp

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- language-lua-0.10.0
- language-javascript-0.6.0.9
- language-dot-0.1.0
- fgl-5.5.3.0
- git: git@github.com:jkoppel/language-c.git
  commit: e5bdaaa8cbf28d09962ccd64a50808d8e5032f85
- git: git@github.com:jkoppel/language-java.git
  commit: 68e71843294b233c36b3cbe52d9b1e35a5898997
- git: git@github.com:bjpop/language-python.git
  commit: 9269c77ca67c52280314a122cae1b3fa1a044168
- mainland-pretty-0.6
- prettyprinter-1.3.0@sha256:ec5617044a1088a37d009d005ed84159b67f18f47bfdac85fb428ec2a80c0788,5503
- megaparsec-6.2.0
- parser-combinators-0.4.0@sha256:1d00d033d17f64477fa262e582dd99a84fe0d7485b5c5cba18cd947472a74944,1584

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
