name:                yogo
version:             0.1.0.0
github:              "githubuser/yogo"
license:             BSD3
author:              Pond Premtoon
maintainer:          vpremt@gmail.com
copyright:           2019 Pond Premtoon

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/yogo#readme>

dependencies:
- base
- compstrat
- containers
- cubix
- cubix-compdata
- lens
- mtl
- transformers

library:
  source-dirs: src
  exposed-modules:
    - Generic
    - Python

executables:
  yogo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yogo

tests:
  yogo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yogo
